openapi: 3.0.3
info:
  title: FoodCourt Management API
  description: API para gestión de restaurantes y platos - Plazoleta de comidas
  version: 1.0.0
  contact:
    name: Pragma PowerUp Team

servers:
  - url: http://localhost:8080
    description: Servidor local de desarrollo


paths:
  /restaurants:
    get:
      tags:
        - Restaurants
      summary: Listar restaurantes
      description: Lista todos los restaurantes disponibles ordenados alfabéticamente
      operationId: listRestaurants
      parameters:
        - name: page
          in: query
          description: Número de página (empezando en 0)
          required: false
          schema:
            type: integer
            default: 0
            minimum: 0
        - name: size
          in: query
          description: Cantidad de elementos por página
          required: false
          schema:
            type: integer
            default: 10
            minimum: 1
            maximum: 100
      responses:
        '200':
          description: Lista de restaurantes obtenida exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestaurantListResponse'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      tags:
        - Restaurants
      summary: Crear un nuevo restaurante
      description: Crea un nuevo restaurante en el sistema (solo usuarios con rol propietario)
      operationId: createRestaurant
      requestBody:
        description: Datos del restaurante a crear
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RestaurantRequest'
      responses:
        '201':
          description: Restaurante creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestaurantDataResponse'
        '400':
          description: Datos de entrada inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /restaurants/{restaurantId}/dishes:
    get:
      tags:
        - Dishes
      summary: Listar platos de un restaurante
      description: Lista los platos de un restaurante específico, con paginación y filtro opcional por categoría
      operationId: listDishesByRestaurant
      parameters:
        - name: restaurantId
          in: path
          description: ID del restaurante
          required: true
          schema:
            type: integer
            format: int64
        - name: page
          in: query
          description: Número de página (empezando en 0)
          required: false
          schema:
            type: integer
            default: 0
            minimum: 0
        - name: size
          in: query
          description: Cantidad de elementos por página
          required: false
          schema:
            type: integer
            default: 10
            minimum: 1
            maximum: 100
        - name: category
          in: query
          description: Filtrar por categoría (opcional)
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Lista de platos obtenida exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DishListResponse'
        '404':
          description: Restaurante no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /dishes:
    post:
      tags:
        - Dishes
      summary: Crear un nuevo plato
      description: Crea un nuevo plato en un restaurante (solo propietario del restaurante)
      operationId: createDish
      requestBody:
        description: Datos del plato a crear
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DishRequest'
      responses:
        '201':
          description: Plato creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DishDataResponse'
        '400':
          description: Datos de entrada inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /dishes/{id}:
    patch:
      tags:
        - Dishes
      summary: Actualizar precio y descripción de un plato
      description: Actualiza el precio y/o descripción de un plato (solo propietario del restaurante)
      operationId: updateDish
      parameters:
        - name: id
          in: path
          description: ID del plato a actualizar
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Datos del plato a actualizar
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DishUpdateRequest'
      responses:
        '200':
          description: Plato actualizado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DishDataResponse'
        '400':
          description: Datos de entrada inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Plato no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /dishes/{id}/toggle:
    patch:
      tags:
        - Dishes
      summary: Activar o desactivar un plato
      description: Permite activar o desactivar el estado de un plato existente
      operationId: toggleDishStatus
      parameters:
        - name: id
          in: path
          description: ID del plato
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Estado del plato actualizado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToggleDishResponse'
        '400':
          description: Datos de entrada inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Plato no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /orders:
    post:
      tags:
        - Orders
      summary: Crear una nueva orden
      description: Crea una nueva orden en un restaurante
      operationId: createOrder
      requestBody:
        description: Datos de la orden a crear
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderRequest'
      responses:
        '201':
          description: Orden creada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderDataResponse'
        '400':
          description: Datos de entrada inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    RestaurantRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
          description: Nombre del restaurante (puede contener números pero no solo números)
          example: "Restaurante El Buen Sabor"
        nit:
          type: string
          pattern: '^[0-9]+$'
          maxLength: 20
          description: NIT del restaurante (solo números)
          example: "9001234567"
        address:
          type: string
          minLength: 1
          maxLength: 200
          description: Dirección del restaurante
          example: "Calle 123 #45-67"
        phoneNumber:
          type: string
          maxLength: 13
          pattern: '^\+?[0-9]{1,13}$'
          description: Teléfono del restaurante (máximo 13 caracteres, puede contener +)
          example: "+573001234567"
        urlLogo:
          type: string
          maxLength: 500
          description: URL del logo del restaurante
          example: "https://example.com/logo.png"
        ownerId:
          type: integer
          format: int64
          description: ID del usuario propietario del restaurante
          example: 1
      required:
        - name
        - nit
        - address
        - phoneNumber
        - urlLogo
        - ownerId

    RestaurantResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID único del restaurante
          example: 1
        name:
          type: string
          description: Nombre del restaurante
          example: "Restaurante El Buen Sabor"
        nit:
          type: string
          description: NIT del restaurante
          example: "9001234567"
        address:
          type: string
          description: Dirección del restaurante
          example: "Calle 123 #45-67"
        phoneNumber:
          type: string
          description: Teléfono del restaurante
          example: "+573001234567"
        urlLogo:
          type: string
          description: URL del logo del restaurante
          example: "https://example.com/logo.png"
        ownerId:
          type: integer
          format: int64
          description: ID del usuario propietario
          example: 1

    RestaurantDataResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/RestaurantResponse'
        message:
          type: string
          example: "Restaurante creado exitosamente"

    RestaurantLiteResponse:
      type: object
      properties:
        name:
          type: string
          description: Nombre del restaurante
          example: "Restaurante El Buen Sabor"
        urlLogo:
          type: string
          description: URL del logo del restaurante
          example: "https://example.com/logo.png"

    RestaurantListResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/RestaurantLiteResponse'
        page:
          type: integer
          description: Número de página actual
          example: 0
        size:
          type: integer
          description: Cantidad de elementos por página
          example: 10
        totalElements:
          type: integer
          format: int64
          description: Total de elementos
          example: 50
        totalPages:
          type: integer
          description: Total de páginas
          example: 5
        last:
          type: boolean
          description: Indica si es la última página
          example: false

    DishRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
          description: Nombre del plato
          example: "Bandeja Paisa"
        price:
          type: integer
          minimum: 1
          description: Precio del plato en números enteros positivos mayores a 0
          example: 25000
        description:
          type: string
          minLength: 1
          maxLength: 500
          description: Descripción del plato
          example: "Deliciosa bandeja paisa tradicional con todos los ingredientes"
        urlImage:
          type: string
          maxLength: 500
          description: URL de la imagen del plato
          example: "https://example.com/bandeja-paisa.jpg"
        category:
          type: string
          description: Categoría del plato
          example: "PLATOS_FUERTES"
        restaurantId:
          type: integer
          format: int64
          description: ID del restaurante al que pertenece el plato
          example: 1
      required:
        - name
        - price
        - description
        - urlImage
        - category
        - restaurantId

    DishUpdateRequest:
      type: object
      properties:
        price:
          type: integer
          minimum: 1
          description: Nuevo precio del plato
          example: 28000
        description:
          type: string
          minLength: 1
          maxLength: 500
          description: Nueva descripción del plato
          example: "Bandeja paisa mejorada con ingredientes premium"

    DishResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID único del plato
          example: 1
        name:
          type: string
          description: Nombre del plato
          example: "Bandeja Paisa"
        price:
          type: integer
          description: Precio del plato
          example: 25000
        description:
          type: string
          description: Descripción del plato
          example: "Deliciosa bandeja paisa tradicional"
        urlImage:
          type: string
          description: URL de la imagen del plato
          example: "https://example.com/bandeja-paisa.jpg"
        category:
          type: string
          description: Categoría del plato
          example: "PLATOS_FUERTES"
        active:
          type: boolean
          description: Indica si el plato está activo
          example: true
        restaurantId:
          type: integer
          format: int64
          description: ID del restaurante
          example: 1

    ToggleDishResponse:
        type: object
        properties:
            id:
              type: integer
              format: int64
              description: ID del plato
            active:
              type: boolean
              description: Nuevo estado del plato (true = activo, false = inactivo)
              example: false

    DishDataResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/DishResponse'
        message:
          type: string
          example: "Plato creado exitosamente"

    DishListResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/DishResponse'
        page:
          type: integer
          description: Número de página actual
          example: 0
        size:
          type: integer
          description: Cantidad de elementos por página
          example: 10
        totalElements:
          type: integer
          format: int64
          description: Total de elementos
          example: 100
        totalPages:
          type: integer
          description: Total de páginas
          example: 10
        last:
          type: boolean
          description: Indica si es la última página
          example: false

    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
          description: Timestamp del error
          example: "2025-11-30T10:30:00Z"
        status:
          type: integer
          description: Código de estado HTTP
          example: 400
        error:
          type: string
          description: Tipo de error
          example: "Bad Request"
        message:
          type: string
          description: Mensaje descriptivo del error
          example: "El campo 'name' es requerido"
        path:
          type: string
          description: Path de la petición que causó el error
          example: "/api/v1/restaurants"

    OrderRequest:
      type: object
      properties:
        restaurantId:
          type: integer
          format: int64
          description: ID del restaurante
          example: 1
        dishes:
          type: array
          items:
            $ref: '#/components/schemas/OrderDishRequest'
          description: Lista de platos en la orden
      required:
        - restaurantId
        - dishes

    OrderDishRequest:
      type: object
      properties:
        dishId:
          type: integer
          format: int64
          description: ID del plato
          example: 5
        quantity:
          type: integer
          minimum: 1
          description: Cantidad de ese plato en la orden
          example: 2
      required:
        - dishId
        - quantity

    OrderResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID único de la orden
          example: 100
        restaurantId:
          type: integer
          format: int64
          description: ID del restaurante
          example: 1
        client:
          type: integer
          format: int64
          description: ID del cliente
          example: 10
        employee:
          type: integer
          format: int64
          description: ID del empleado asignado (puede ser null)
          example: 20
        status:
          type: string
          description: Estado de la orden
          example: "PENDING"
        dishes:
          type: array
          items:
            $ref: '#/components/schemas/OrderDishRequest'
        createdAt:
          type: string
          format: local-date-time
          description: Fecha y hora de creación
          example: "2025-12-01T10:30:00Z"

    OrderDataResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/OrderResponse'
        message:
          type: string
          example: "Orden creada exitosamente"
